workflows:
  ios-preview:
    name: iOS Preview
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Build iOS Simulator Preview
        script: |
          flutter build ios --debug --simulator --dart-define=APP_PREVIEW_SAFE_MODE=true